site_name: "ifvlaboratory-docs"
site_url: "https://docs.ifvlab.com/"
site_description: "IFVLAB Documentation"
site_author: "IFVLAB"

repo_url: "https://github.com/ifvlaboratory/docs/"

nav:
  - Start: "index.md"

theme:
  name: "material"
  language: "en"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "deep orange"
      accent: "deep orange"
      toggle:
        icon: "material/brightness-7"
        name: "Switch to dark mode"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      accent: "indigo"
      toggle:
        icon: "material/brightness-4"
        name: "Switch to light mode"

extra:
  alternate:
    - name: "English"
      link: "/en/"
    - name: "簡體中文"
      link: "/zh/"
      lang: "zh"
    - name: "繁體中文"
      link: "/zh-TW/"
      lang: "zh-TW"
  analytics:
    provider: "google"
    property: "G-H2FJ5C1Q3N"

markdown_extensions:  
  - toc:       
      toc_depth: '2'
