site_name: xiaomai-bot-docs-cn
site_url: https://docs.ifvlab.com/projects/xiaomai/
site_description: xiaomai-bot documention
site_author: IFVLAB members

repo_url: https://github.com/ifvlaboratory/xiaomai-bot-docs/

nav:
  - Start: "index.md"

theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-H2FJ5C1Q3N

markdown_extensions:  
  - toc:       
      toc_depth: '2'
